### ISSUE TITLE
WP 4.4 term meta

### ISSUE THREAD

**Issue by GaryJones** [benhuson/Taxonomy-Images#25]
WP 4.4 obviously officially supports term meta. Might you switch over to using this, so it becomes standard, for those that run the plugin on 4.4+?

**Comment by benhuson** [comment]
Yep, planning to add support for that.

Just need to write an upgrade script for existing users who upgrade.

**Comment by benhuson** [comment]
Plan of action:

- [ ] Hook into get_term_meta to return image ID from current data structure.
- [ ] Add a Taxonomy Images Meta class to handle new term meta functions with legacy data fallback.
- [ ] Migrate data to term meta if supported

**Comment by jaredatch** [comment]
:+1:

**Comment by jaredatch** [comment]
Any chance this is still planned?

**Comment by benhuson** [comment]
Yep. I nearly have a version working that allows the use of the new WordPress `get_term_meta()` functions, but currently hooks into the existing options-based data. When I've tested that I'll make that available as a release.

Then I'll work in a migration routine to move the options-based data to 'real' term meta in a following release.

**Comment by benhuson** [comment]
If you'd like to test term meta support, please  download and try this branch:
https://github.com/benhuson/Taxonomy-Images/tree/feature/term-api

You will then be able to get the ID for an image and output it like this:

```
$image_id = get_term_meta( $term_id, 'taxonomy_image_id', true );
echo wp_get_attachment_image( $image_id, 'thumbnail' );
```

**Comment by jaredatch** [comment]
Will do 👍
